development:
  sessions:
    default:
      uri: 'mongodb://djiango:showblog210@kahana.mongohq.com:10053/blog'
production:
  sessions:
    default:
      uri: 'mongodb://djiango:showblog210@kahana.mongohq.com:10053/blog'