development:
  sessions:
    default:
      uri: 'mongodb://djiango:showblog210@kahana.mongohq.com:10053/blog'
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      uri: 'mongodb://djiango:showblog210@kahana.mongohq.com:10053/blog'
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: idb
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
